[package]
name = "rest1"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rusqlite = { version = "0.28", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
